name: Build and Test Unreal Project

on:
  push:
  pull_request:    
  workflow_dispatch:

env:
  AWS_REGION: eu-central-1
  
jobs:
  start_ecs_task:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Send Webhook to AWS
        uses: GuyErreich/Send-Webhook@master
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          aws_region: us-east-1
          aws_role_to_assume: arn:aws:iam::961341519925:role/GitHubActionsSecretManagerRole
          secret_name: github/webhook_token
          content_type: application/json
          headers: '{"X-GitHub-Event": "push"}'
          payload: '{"message": "Hello, world!"}'
      
  # build:
  #   runs-on: [self-hosted, linux]  # Use a GitHub-hosted runner
  #   needs: [start_ecs_task]
  #   if: ${{ github.event_name == 'push' || always() }}
  #   permissions: read-all
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #       with:
  #         clean: true
  #         # lfs: true

  #     - name: Hello World
  #       run: echo 'Hello World!'
        
  #     - name: Show unreal engine folder
  #       run: ls -la

  #     - name: Build project
  #       run: task -d $HOME clean build


  
