name: Build and Test Unreal Project

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AWS_REGION: eu-central-1
  
jobs:
  start_ecs_task:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::961341519925:role/GitHubActionsECSUpdateRole
          aws-region: ${{ env.AWS_REGION }}
          
      - name: Get current desired count
        id: check_desired_count
        run: |
          desired_count=$(aws ecs describe-services \
          --cluster fargate-cluster \
          --services unreal_engine \
          | jq ".services[] | select(.serviceName == \"unreal_engine\") | .desiredCount")
          echo "Desired count is $desired_count"
          echo "desired_count=$desired_count" >> $GITHUB_OUTPUT
        

      - name: Update desired count
        run: |
          desired_count=${{ steps.check_desired_count.outputs.desired_count }}
          incremented_count=$((desired_count + 1))
          aws ecs update-service \
            --cluster fargate-cluster \
            --service unreal_engine \
            --desired-count $desired_count \
            > /dev/null 2>&1
          echo "New desired count is $incremented_count"
      
  build:
    runs-on: [self-hosted, linux]  # Use a GitHub-hosted runner
    needs: [start_ecs_task]
    permissions: read-all
    outputs:
      task_id: ${{ steps.step1.outputs.test }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Hello World
        run: echo 'Hello World!'
        
      - name: Show unreal engine folder
        run: ls -la

      - name: Build project
        run: task -d $HOME build

  stop_ecs_task:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    needs: [build]
    if: always()
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::961341519925:role/GitHubActionsECSUpdateRole
          aws-region: ${{ env.AWS_REGION }}
          
      - name: Check current desired count
        id: check_desired_count
        run: |
          desired_count=$(aws ecs describe-services \
          --cluster fargate-cluster \
          --services unreal_engine \
          | jq ".services[] | select(.serviceName == \"unreal_engine\") | .desiredCount")
          echo "Desired count is $desired_count"
          echo "desired_count=$desired_count" >> $GITHUB_OUTPUT      

      - name: Stop current runner task
        run: |
          TASK_METADATA=$(curl -s "$ECS_CONTAINER_METADATA_URI_V4/task")
          TASK_ID=$(echo "$TASK_METADATA" | jq -r '.TaskARN' | awk -F'/' '{print $3}')
          echo $TASK_ID
        # aws ecs stop-task \
        #   --cluster fargate-cluster \
        #   --task $TASK_ID \
        #   --reason "GitHub action has finished with status: ${{ env.Status }}"
        
      - name: Update desired count
        run: |
          desired_count=${{ steps.check_desired_count.outputs.desired_count }}
          decremented_count=$((desired_count + 1))
          aws ecs update-service \
            --cluster fargate-cluster \
            --service unreal_engine \
            --desired-count $desired_count \
            > /dev/null 2>&1
          echo "New desired count is $decremented_count"
