name: Build and Test Unreal Project

on:
  push:
    branches:
      - main
  workflow_dispatch:
    

jobs:
  start_ecs_service:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::961341519925:role/GitHubActionsECSUpdateRole
          aws-region: eu-central-1

      - name: Update ECS service desired count
        run: |
          aws ecs update-service \
            --cluster fargate-cluster \
            --service unreal_engine \
            --desired-count 1
  build:
    runs-on: [self-hosted, linux]  # Use a GitHub-hosted runner
    # permissions: read-all
    # container:
    #   image: 961341519925.dkr.ecr.eu-central-1.amazonaws.com/ci_cd/unreal_engine:automation-5.4.4  # Pulls your Unreal image from GHCR
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::961341519925:role/GitHubActionsECSUpdateRole
          aws-region: eu-central-1

      - name: Run container from ECR
        uses: docker://961341519925.dkr.ecr.eu-central-1.amazonaws.com/ci_cd/unreal_engine:automation-5.4.4
        with:
          entrypoint: "bash"  # Optional: if you want to override the default entrypoint
          # args: "<your-commands>"
